from time import sleep
import RPi.GPIO as GPIO

DIR = 20
STEP = 21
STEP2 = 26
DIR2 = 12
CW = 0
CCW = 1
delay = .00005
delay2 = 3
delay3 = 15

GPIO.setmode(GPIO.BCM)
GPIO.setup(DIR,GPIO.OUT)
GPIO.setup(STEP,GPIO.OUT)
GPIO.setup(DIR2,GPIO.OUT)
GPIO.setup(STEP2,GPIO.OUT)

for x in range(10000):
	GPIO.output(DIR,CW)
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR,CCW)
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR2,CW)
	GPIO.output(STEP2,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP2,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR2,CCW)
	GPIO.output(STEP2,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP2,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR,CW)
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR,CCW)
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR2,CW)
	GPIO.output(STEP2,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP2,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR2,CCW)
	GPIO.output(STEP2,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP2,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR,CW)
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR,CCW)
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR2,CW)
	GPIO.output(STEP2,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP2,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR2,CCW)
	GPIO.output(STEP2,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP2,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR,CW)
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR,CCW)
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR2,CW)
	GPIO.output(STEP2,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP2,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR2,CCW)
	GPIO.output(STEP2,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP2,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR,CW)
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR,CCW)
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR2,CW)
	GPIO.output(STEP2,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP2,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR2,CCW)
	GPIO.output(STEP2,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP2,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR,CW)
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR,CCW)
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR2,CW)
	GPIO.output(STEP2,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP2,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR2,CCW)
	GPIO.output(STEP2,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP2,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR,CW)
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR,CCW)
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR2,CW)
	GPIO.output(STEP2,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP2,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR2,CCW)
	GPIO.output(STEP2,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP2,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR,CW)
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR,CCW)
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR2,CW)
	GPIO.output(STEP2,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP2,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR2,CCW)
	GPIO.output(STEP2,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP2,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR,CW)
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR,CCW)
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR2,CW)
	GPIO.output(STEP2,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP2,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR2,CCW)
	GPIO.output(STEP2,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP2,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR,CW)
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR,CCW)
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR2,CW)
	GPIO.output(STEP2,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP2,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR2,CCW)
	GPIO.output(STEP2,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP2,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR,CW)
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR,CCW)
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR2,CW)
	GPIO.output(STEP2,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP2,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR2,CCW)
	GPIO.output(STEP2,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP2,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR,CW)
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR,CCW)
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR2,CW)
	GPIO.output(STEP2,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP2,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR2,CCW)
	GPIO.output(STEP2,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP2,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR,CW)
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR,CCW)
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR2,CW)
	GPIO.output(STEP2,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP2,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR2,CCW)
	GPIO.output(STEP2,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP2,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR,CW)
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR,CCW)
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR2,CW)
	GPIO.output(STEP2,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP2,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(10000):
	GPIO.output(DIR2,CCW)
	GPIO.output(STEP2,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP2,GPIO.LOW)
	sleep(delay)
sleep(delay2)
