from time import sleep
import RPi.GPIO as GPIO

DIR = 20    # Direction GPIO Pin
STEP = 21   # Step GPIO Pin
CW = 0      # Counter Clockwise
STEPS = 1000  # Number of gimbal steps

GPIO.setmode(GPIO.BCM)
GPIO.setup(DIR,GPIO.OUT)
GPIO.setup(STEP,GPIO.OUT)
GPIO.output(DIR,CW)

step_count = STEPS
delay =.0208
delay2 = 10

for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(step_count):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
GPIO.cleanup()