from time import sleep
import RPi.GPIO as GPIO

DIR = 20
STEP = 21
CW = 0
delay = .00005
delay2 = 5
delay3 = 15

GPIO.setmode(GPIO.BCM)
GPIO.setup(DIR,GPIO.OUT)
GPIO.setup(STEP,GPIO.OUT)
GPIO.output(DIR,CW)

for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
for x in range(200):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(400):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(600):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(800):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay2)
for x in range(1000):
	GPIO.output(STEP,GPIO.HIGH)
	sleep(delay)
	GPIO.output(STEP,GPIO.LOW)
	sleep(delay)
sleep(delay3)
GPIO.cleanup()
